### ISSUE TITLE
Add print all composers in all projects in directory

### ISSUE THREAD

**Issue by mirouml** [DelazJ/MapsPrinter#1]
First thank you for this plugin, works great for me. I did very similar tool for Mapinfo but it works for all layouts in all workspaces in directory. So all you need is to select directory and which format you want and it will pdf/jpg... everything.

Now, at this point I consider myself as beginner with python, I believe I am able to adjust this plugin to fit our needs but it probably won't be "high standard" code adjustments. So I am wondering if there is some chance you would add this option? Or interested in me to pull request once I am done with my "try"?

**Comment by DelazJ** [comment]
Hi Miroslav
Happy to know that this plugin is useful for you.

I'm also a beginner with Python and Maps Printer is the first project I
worked on and I'm pretty sure my code is not really "high standard" :). The
next feature I'm trying to add is a better management of atlas printing
within the opened project.

Due to my current level, I'm not really sure I can easily deal with the
feature you are asking for. But maybe, together we can do such a thing
(discuss about the way you think it should be implemented). So yes, you can
freely fork this project and add changes you think useful and pull request
once you are done. At that moment, I think we can also ask help from some
Python guru in the community.

**Comment by mirouml** [comment]
Great, thank you. At this moment I need to finish few other tools first which has bit higher priority for me. It involves exploiting of some parts of QGIS contour plugin so it is actually helping me to grasp bit more about how the whole QGIS plugins world works. I should get to this in maximum few weeks and will definitely fork the result (right after I find out what it really means and how to do it here). Thanks again.

**Comment by DelazJ** [comment]
Fixed in #19
